# Supported funding model platforms
# See: https://docs.github.com/en/repositories/managing-your-repositorys-
# settings-and-features/customizing-your-repository/displaying-a-sponsor-
# button-in-your-repository

# github: # GitHub Sponsors usernames, e.g. [user1, user2]
# custom: # Custom sponsorship URLs, e.g. ['https://link1', 'https://link2']
